language: csharp
dotnet: 2.1.401
os: linux
mono: none
dist: trusty
env:
 global:
  - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  - DOTNET_CLI_TELEMETRY_OPTOUT: 1

script:
 - dotnet restore
 - dotnet build
 - ./ut.sh

deploy:
 - provider: script
   script: ./deploy-branch.sh
   on:
    branch: develop
 - provider: script
   script: ./deploy-tag.sh
   on:
    tags: true